version: '3.8'
services:
  backend:
    container_name: "django-backend"
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./backend/django_app:/backend/django_app
      - ./backend/plugin_system:/backend/plugin_system
      - ./backend/startscript.sh:/startscript.sh
    command: /startscript.sh
    ports:
      - "8080:8080"
    links:
      - redis

  frontend:
    container_name: "node-frontend"
    build:
      context: .
      dockerfile: frontend.Dockerfile
    command: npm run dev -- --host
    ports:
      - "5173:5173"
  redis:
    container_name: redis
    image: "redis:alpine"  

#celery -A django_app worker --loglevel=INFO