# Generated by Django 4.2.1 on 2023-05-26 08:50

from django.db import migrations, models
import django.db.models.deletion
import django_app.webserver.models.uploaded_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingFilesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('request_id', models.CharField(max_length=64)),
                ('date_of_request', models.DateTimeField(auto_now_add=True)),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Processing Files Requests',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('valid_file_endings', models.TextField(default='')),
                ('uploaded_file', models.FileField(max_length=255, upload_to=django_app.webserver.models.uploaded_file.get_uploaded_file_path)),
                ('date_of_upload', models.DateTimeField(auto_now_add=True)),
                ('processing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.processingfilesrequest')),
            ],
            options={
                'verbose_name_plural': 'Uploaded files',
            },
        ),
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('processed_file_path', models.TextField()),
                ('date_of_upload', models.DateTimeField(auto_now_add=True)),
                ('merger', models.BooleanField(default=False)),
                ('processing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.processingfilesrequest')),
            ],
            options={
                'verbose_name_plural': 'Processed files',
            },
        ),
    ]
