# Generated by Django 4.2.4 on 2023-09-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingfilesrequest',
            name='task_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='user_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='processing_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webserver.processingfilesrequest'),
        ),
    ]
