# Generated by Django 3.2.12 on 2022-09-06 20:20

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('user_id', models.CharField(max_length=64)),
                ('finished', models.BooleanField(default=False)),
                ('uploaded_file', models.ImageField(upload_to=application.models.get_directory_to_save_file_in)),
                ('date_of_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
