# Generated by Django 4.1.1 on 2022-09-07 08:29

import application.models
import application.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('user_id', models.CharField(max_length=64)),
                ('finished', models.BooleanField(default=False)),
                ('uploaded_file', models.ImageField(upload_to=application.models.get_directory_to_save_file_in, validators=[application.validators.validate_file_extension])),
                ('date_of_upload', models.DateTimeField(auto_now_add=True)),
                ('csrf_token', models.CharField(max_length=32)),
            ],
        ),
    ]
