# Generated by Django 3.2.12 on 2022-09-07 01:47

import application.models
import application.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_file',
            field=models.ImageField(upload_to=application.models.get_directory_to_save_file_in, validators=[application.validators.validate_file_extension]),
        ),
    ]
