@startuml

    title Most important Components
    component Browser #pink
    component Django #lightblue
    component TaskScheduler #violet
    component Processors
    component Plugin #lightgreen
    component ProcessingEventHandler
    database models.sqlite3
    database tasks.sqlite3

    Django --> models.sqlite3: creates
    Django --> tasks.sqlite3: adds tasks
    Plugin -> Django: serves formular
    Plugin -up.> Processors: has

    Browser -> Django: requests data
    Browser -> Django: shows templates
    Browser -> Django: uploaded Files
    Browser -> Django: sends formular
    TaskScheduler -> Processors: runs / schedules
    TaskScheduler -> tasks.sqlite3: checks and executes
    ProcessingEventHandler -> Django: sends requests

    Processors -> [ProcessingEventHandler]: signal events
    Processors -down-> models.sqlite3: processes
@enduml